#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xCFDF148828C642A7 (alanc@freedesktop.org)
#
Name     : libXxf86dga
Version  : 1.1.5
Release  : 9
URL      : https://www.x.org/releases/individual/lib/libXxf86dga-1.1.5.tar.gz
Source0  : https://www.x.org/releases/individual/lib/libXxf86dga-1.1.5.tar.gz
Source99 : https://www.x.org/releases/individual/lib/libXxf86dga-1.1.5.tar.gz.sig
Summary  : X11 Direct Graphics Access extension library
Group    : Development/Tools
License  : MIT
Requires: libXxf86dga-lib = %{version}-%{release}
Requires: libXxf86dga-license = %{version}-%{release}
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : pkg-config
BuildRequires : pkgconfig(32x11)
BuildRequires : pkgconfig(32xext)
BuildRequires : pkgconfig(32xextproto)
BuildRequires : pkgconfig(32xf86dgaproto)
BuildRequires : pkgconfig(32xorg-macros)
BuildRequires : pkgconfig(32xproto)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xextproto)
BuildRequires : pkgconfig(xf86dgaproto)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)

%description
libXxf86dga - Client library for the XFree86-DGA extension.
-----------------------------------------------------------

%package dev
Summary: dev components for the libXxf86dga package.
Group: Development
Requires: libXxf86dga-lib = %{version}-%{release}
Provides: libXxf86dga-devel = %{version}-%{release}
Requires: libXxf86dga = %{version}-%{release}

%description dev
dev components for the libXxf86dga package.


%package dev32
Summary: dev32 components for the libXxf86dga package.
Group: Default
Requires: libXxf86dga-lib32 = %{version}-%{release}
Requires: libXxf86dga-dev = %{version}-%{release}

%description dev32
dev32 components for the libXxf86dga package.


%package lib
Summary: lib components for the libXxf86dga package.
Group: Libraries
Requires: libXxf86dga-license = %{version}-%{release}

%description lib
lib components for the libXxf86dga package.


%package lib32
Summary: lib32 components for the libXxf86dga package.
Group: Default
Requires: libXxf86dga-license = %{version}-%{release}

%description lib32
lib32 components for the libXxf86dga package.


%package license
Summary: license components for the libXxf86dga package.
Group: Default

%description license
license components for the libXxf86dga package.


%prep
%setup -q -n libXxf86dga-1.1.5
pushd ..
cp -a libXxf86dga-1.1.5 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1552793819
export LDFLAGS="${LDFLAGS} -fno-lto"
export CFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export FFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
%configure --disable-static
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check
cd ../build32;
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1552793819
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libXxf86dga
cp COPYING %{buildroot}/usr/share/package-licenses/libXxf86dga/COPYING
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/Xxf86dga.h
/usr/include/X11/extensions/xf86dga1.h
/usr/lib64/libXxf86dga.so
/usr/lib64/pkgconfig/xxf86dga.pc
/usr/share/man/man3/XDGA.3
/usr/share/man/man3/XDGAChangePixmapMode.3
/usr/share/man/man3/XDGACloseFramebuffer.3
/usr/share/man/man3/XDGACopyArea.3
/usr/share/man/man3/XDGACopyTransparentArea.3
/usr/share/man/man3/XDGACreateColormap.3
/usr/share/man/man3/XDGAFillRectangle.3
/usr/share/man/man3/XDGAGetViewportStatus.3
/usr/share/man/man3/XDGAInstallColormap.3
/usr/share/man/man3/XDGAKeyEventToXKeyEvent.3
/usr/share/man/man3/XDGAOpenFramebuffer.3
/usr/share/man/man3/XDGAQueryExtension.3
/usr/share/man/man3/XDGAQueryModes.3
/usr/share/man/man3/XDGAQueryVersion.3
/usr/share/man/man3/XDGASelectInput.3
/usr/share/man/man3/XDGASetClientVersion.3
/usr/share/man/man3/XDGASetMode.3
/usr/share/man/man3/XDGASetViewport.3
/usr/share/man/man3/XDGASync.3
/usr/share/man/man3/XF86DGA.3
/usr/share/man/man3/XFree86-DGA.3

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libXxf86dga.so
/usr/lib32/pkgconfig/32xxf86dga.pc
/usr/lib32/pkgconfig/xxf86dga.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libXxf86dga.so.1
/usr/lib64/libXxf86dga.so.1.0.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libXxf86dga.so.1
/usr/lib32/libXxf86dga.so.1.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libXxf86dga/COPYING
