#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libXxf86dga
Version  : 1.1.4
Release  : 3
URL      : https://www.x.org/releases/individual/lib/libXxf86dga-1.1.4.tar.gz
Source0  : https://www.x.org/releases/individual/lib/libXxf86dga-1.1.4.tar.gz
Summary  : XFree86 Direct Graphics Access Extension Library
Group    : Development/Tools
License  : MIT
Requires: libXxf86dga-lib
Requires: libXxf86dga-doc
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xextproto)
BuildRequires : pkgconfig(xf86dgaproto)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)

%description
libXxf86dga - Client library for the XFree86-DGA extension.
All questions regarding this software should be directed at the
Xorg mailing list:

%package dev
Summary: dev components for the libXxf86dga package.
Group: Development
Requires: libXxf86dga-lib
Provides: libXxf86dga-devel

%description dev
dev components for the libXxf86dga package.


%package doc
Summary: doc components for the libXxf86dga package.
Group: Documentation

%description doc
doc components for the libXxf86dga package.


%package lib
Summary: lib components for the libXxf86dga package.
Group: Libraries

%description lib
lib components for the libXxf86dga package.


%prep
%setup -q -n libXxf86dga-1.1.4

%build
export LANG=C
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/Xxf86dga.h
/usr/include/X11/extensions/xf86dga1.h
/usr/lib64/libXxf86dga.so
/usr/lib64/pkgconfig/xxf86dga.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libXxf86dga.so.1
/usr/lib64/libXxf86dga.so.1.0.0
